# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model_pb2 as model__pb2


class ChatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.client_receive_message = channel.unary_unary(
                '/model.Chat/client_receive_message',
                request_serializer=model__pb2.Text.SerializeToString,
                response_deserializer=model__pb2.Note.FromString,
                )
        self.client_send_message = channel.unary_unary(
                '/model.Chat/client_send_message',
                request_serializer=model__pb2.Note.SerializeToString,
                response_deserializer=model__pb2.Text.FromString,
                )


class ChatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def client_receive_message(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def client_send_message(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'client_receive_message': grpc.unary_unary_rpc_method_handler(
                    servicer.client_receive_message,
                    request_deserializer=model__pb2.Text.FromString,
                    response_serializer=model__pb2.Note.SerializeToString,
            ),
            'client_send_message': grpc.unary_unary_rpc_method_handler(
                    servicer.client_send_message,
                    request_deserializer=model__pb2.Note.FromString,
                    response_serializer=model__pb2.Text.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.Chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def client_receive_message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.Chat/client_receive_message',
            model__pb2.Text.SerializeToString,
            model__pb2.Note.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def client_send_message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.Chat/client_send_message',
            model__pb2.Note.SerializeToString,
            model__pb2.Text.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
